; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EasyKit"
#define MyAppVersion "4.2.3"
#define MyAppPublisher "LoveDoLove"
#define MyAppURL "https://github.com/LoveDoLove/EasyKit"
#define MyAppExeName "EasyKit.exe"

; x64 Release Inno Setup Script
#define MyArch "x64"
#define MyDefaultDir "{commonpf64}\EasyKit"

#include "Common.iss"
