; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EasyKit"
#define MyAppVersion "4.2.3"
#define MyAppPublisher "LoveDoLove"
#define MyAppURL "https://github.com/LoveDoLove/EasyKit"
#define MyAppExeName "EasyKit.exe"

; x86 Release Inno Setup Script
#define MyArch "x86"
#define MyDefaultDir "{commonpf32}\EasyKit"
#define MyRegFile "{#MySourcePath}\ContextMenu-win-x86.reg"
#define MyRegFileName "ContextMenu-win-x86.reg"
#define MyPublishFolder "{#MySourcePath}\..\publish\win-x86\"

#ifdef MySourcePath
  #include "Common.iss"
#else
  #error "MySourcePath must be defined"
#endif
