; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EasyKit"
#define MyAppVersion "4.2.2"
#define MyAppPublisher "LoveDoLove"
#define MyAppURL "https://github.com/LoveDoLove/EasyKit"
#define MyAppExeName "EasyKit.exe"

; x64 Release Inno Setup Script
#define MyArch "x64"
#define MyDefaultDir "{commonpf64}\EasyKit"
#define MyRegFile "{#MySourcePath}\ContextMenu-win-x64.reg"
#define MyRegFileName "ContextMenu-win-x64.reg"
#define MyPublishFolder "{#MySourcePath}\..\publish\win-x64\"

#ifdef MySourcePath
  #include "Common.iss"
#else
  #error "MySourcePath must be defined"
#endif
