name: Build and Upload EasyKit 
 
on: 
  push: 
    branches: [ main ] 
    tags: [ 'v*' ] 
  pull_request: 
    branches: [ main ] 
  workflow_dispatch: 
 
jobs: 
  build: 
    name: Build EasyKit Packages 
    runs-on: windows-latest 
 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4 
 
      - name: Create build directory 
        run: mkdir -p build 
 
      - name: Fix NSIS script 
        shell: powershell 
        run: | 
          # Create a modified version of the NSIS script without EnVar plugin usage 
          $content = Get-Content -Path ./EasyKit.nsi -Raw 
          $content = $content -replace 'OutFile "dist\\EasyKit_Setup.exe"', 'OutFile "build\EasyKit_Setup.exe"' 
          # Comment out the EnVar plugin section 
          $content = $content -replace 'Section "Add to PATH" SecPath', '; Section "Add to PATH" SecPath - Disabled in CI' 
          $content = $content -replace 'EnVar::AddValue "PATH" "\$INSTDIR"', '; EnVar::AddValue "PATH" "$INSTDIR"' 
          # Remove the PATH section description 
          $content = $content -replace '!insertmacro MUI_DESCRIPTION_TEXT \$\{SecPath\} ".*?"', '; PATH section description removed' 
          # Remove EnVar from uninstaller section 
          $content = $content -replace 'EnVar::DeleteValue "PATH" "\$INSTDIR"', '; EnVar::DeleteValue "PATH" "$INSTDIR" - Removed for CI compatibility' 
          Set-Content -Path ./EasyKit.nsi -Value $content 
 
      - name: Setup NSIS 
        uses: joncloud/makensis-action@v4 
 
      - name: Build installer 
        run: makensis EasyKit.nsi 
 
      - name: Upload artifacts 
        uses: actions/upload-artifact@v3 
        with: 
          name: EasyKit-Installer 
          path: build/EasyKit_Setup.exe 
