name: Build and Upload EasyKit 
 
on: 
  push: 
    branches: [ main ] 
    tags: [ 'v*' ] 
  pull_request: 
    branches: [ main ] 
  workflow_dispatch: 
 
jobs: 
  build: 
    name: Build EasyKit Packages 
    runs-on: windows-latest 
    permissions: 
      contents: write 
 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4 
 
      - name: Create build directory 
        run: mkdir build 
        shell: cmd 
 
      - name: Setup build environment 
        shell: cmd 
        run: | 
          IF NOT EXIST scripts\build mkdir scripts\build 
          IF NOT EXIST scripts\build\release_v1.2.8.bat ( 
            echo @echo off > scripts\build\release_v1.2.8.bat 
            echo echo EasyKit Release v1.2.8 >> scripts\build\release_v1.2.8.bat 
            echo echo Build date: %%date%% %%time%% >> scripts\build\release_v1.2.8.bat 
            echo echo. >> scripts\build\release_v1.2.8.bat 
            echo echo This script is part of the EasyKit installation package. >> scripts\build\release_v1.2.8.bat 
            echo echo For more information, visit: https://github.com/LoveDoLove/EasyKit >> scripts\build\release_v1.2.8.bat 
            echo echo. >> scripts\build\release_v1.2.8.bat 
            echo pause >> scripts\build\release_v1.2.8.bat 
          ) 
 
      - name: Install NSIS
        run: | 
          choco install nsis -y 
        shell: pwsh

      - name: Compile NSIS script 
        shell: cmd 
        run: makensis.exe easykit.nsi 
 
      - name: Build ZIP package 
        shell: pwsh 
        run: | 
          Compress-Archive -Path scripts/**/*.bat,run_eskit.bat,README.md,LICENSE,images/* -DestinationPath build\EasyKit.zip -Force 
 
      - name: Verify build artifacts 
        shell: pwsh 
        run: | 
          Get-ChildItem -Path "build" 
 
      - name: Upload artifacts 
        uses: actions/upload-artifact@v4 
        with: 
          name: EasyKit-Packages 
          path: | 
            build/EasyKit_Setup.exe 
            build/EasyKit.zip 
          retention-days: 14 
 
  release: 
    name: Create Release 
    if: startsWith(github.ref, 'refs/tags/') 
    needs: build 
    runs-on: windows-latest 
    permissions: 
      contents: write 
 
    steps: 
      - name: Download artifacts 
        uses: actions/download-artifact@v4 
        with: 
          name: EasyKit-Packages 
          path: release-artifacts 
 
      - name: Create GitHub Release 
        uses: softprops/action-gh-release@v1 
        with: 
          files: | 
            release-artifacts/EasyKit.zip 
            release-artifacts/EasyKit_Setup.exe 
          draft: false 
          generate_release_notes: true
