name: Batch File Validation

on:
  push:
    branches: [ main, master, dev, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Validate Batch Files
        run: |
          $ErrorCount = 0
          foreach ($file in Get-ChildItem -Path . -Filter "*.bat" -Recurse) {
              Write-Host "Checking $($file.FullName)..."
              $content = Get-Content $file.FullName -Raw
              
              # Check for common syntax errors
              if ($content -match ':\s*[a-zA-Z]') {
                  Write-Host "Warning: Possible invalid label in $($file.FullName)"
              }
              
              if ($content -match '%[^%]+[^%]') {
                  Write-Host "Error: Unclosed variable in $($file.FullName)"
                  $ErrorCount++
              }
              
              if ($content -match '\)\s*\(') {
                  Write-Host "Warning: Possible missing command between parentheses in $($file.FullName)"
              }
              
              # Execute syntax check (only checks syntax, doesn't run the batch file)
              cmd /c "echo. | $($file.FullName) 2>&1 | findstr /C:""was unexpected"" /C:""not recognized"" /C:""The syntax of the command is incorrect."""
              if ($LASTEXITCODE -ne 1) {
                  Write-Host "Error: Syntax errors detected in $($file.FullName)"
                  $ErrorCount++
              }
          }
          
          if ($ErrorCount -gt 0) {
              Write-Host "Validation failed with $ErrorCount errors."
              exit 1
          } else {
              Write-Host "All batch files passed validation."
          }
        shell: pwsh
